In [ ]:
import pandas as pd
pd.options.display.float_format = "{:,.2f}".format

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/dummy_data.csv")
# Preview the data
df.head()

   customer_id  age region       segment    income  monthly_spend
0            1   56   West  Medium Value 63,353.00       2,411.00
1            2   69   East  Medium Value 64,900.00       2,688.00
2            3   46   East     Low Value 47,074.00       1,147.00
3            4   32  North    High Value 30,267.00       1,671.00
4            5   60  North    High Value 44,233.00       2,753.00

### Grammer of Graphics
1. Data: df
2. Aesthetics
    A. x-axis:
    B. y-axis:

In [3]:
import plotly.express as px

fig = px.scatter(
    data_frame=df, # data
    x="age", # x aesthetic
    y="income", # y aesthetic
    color="segment", # color aesthetic
    size="monthly_spend", # size aesthetic
    facet_col="region", # facet
    trendline="ols", # statistical layer
    title="Relationship Between Customer Age and Income"
)

fig.show()

In [19]:
sales_by_region = (
    df
    .groupby("region", as_index=False)
    .agg(
        total_sales=("monthly_spend", "sum"),
        avg_sales=("monthly_spend", "mean"),
        number_of_customers=("customer_id", "count")
    )
)

sales_by_region

  region  total_sales  avg_sales  number_of_customers
0   East   116,665.00   1,822.89                   64
1  North   142,714.00   1,928.57                   74
2  South   150,435.00   1,979.41                   76
3   West   184,343.00   2,143.52                   86

In [11]:
Y = list(sales_by_region.columns)[len(grouping):]
Y

['total_sales', 'avg_age', 'avg_income', 'number_of_customers']

In [14]:
Y = ['total_sales',	'avg_age',	'avg_income', 'number_of_customers']
# i = Y[3] 

for i in Y:
    fig = px.bar(
    data_frame = sales_by_region,
    x = 'region',
    y = i,
    title= f"{i} By Region"
    )
    fig.show()

In [20]:
fig = px.bar(
    data_frame=sales_by_region,
    x="region",
    y="total_sales",
    title="Total Sales by Region"
)

fig.show()

In [10]:
grouping = ["region","segment"]
sales_by_region = df.groupby(grouping, as_index=False).agg(
    total_sales = ("monthly_spend", "sum"),
    avg_age = ("age","mean"),
    avg_income = ("income", "mean"),
    number_of_customers = ("customer_id","count")  

)

sales_by_region.head()

  region       segment  total_sales  avg_age  avg_income  number_of_customers
0   East    High Value    30,380.00    35.64   45,427.64                   11
1   East     Low Value    41,203.00    39.44   51,505.31                   32
2   East  Medium Value    45,082.00    46.14   54,797.90                   21
3  North    High Value    37,696.00    40.93   44,810.29                   14
4  North     Low Value    36,642.00    45.08   56,712.85                   26

In [8]:
daily_sales = (
    df
    .assign(
        date=pd.date_range(
            start="2026-01-01",
            periods=len(df),
            freq="D"
        )
    )
    .groupby("date", as_index=False)
    .agg(
        sales=("monthly_spend", "sum"),
        number_of_customers=("customer_id", "count"),
        avg_sales=("monthly_spend", "mean")
    )
)

# Round values for cleaner display
daily_sales["sales"] = daily_sales["sales"].round(0)
daily_sales["avg_sales"] = daily_sales["avg_sales"].round(2)

daily_sales.head()

        date    sales  number_of_customers  avg_sales
0 2026-01-01 2,411.00                    1   2,411.00
1 2026-01-02 2,688.00                    1   2,688.00
2 2026-01-03 1,147.00                    1   1,147.00
3 2026-01-04 1,671.00                    1   1,671.00
4 2026-01-05 2,753.00                    1   2,753.00

In [9]:
fig = px.line(
    data_frame=daily_sales,
    x="date",
    y="sales",
    title="Sales Trend Over Time"
)

fig.show()

## Matplotlib for Instacart

In [17]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'